### ISSUE TITLE
How to use libpostal-1.dll after compiled it?

### ISSUE THREAD

**Issue by MonaiThang** [BenK10/libpostal_windows#3]
I followed the step from [here](https://github.com/BenK10/libpostal_windows/issues/1#issuecomment-318866812) and able to compile the library and get the file libpostal-1.dll.

How can I use and call this libraries on Windows and how to install other related libraries such as node-postal on Windows?

Thank you,

**Comment by kevinXYX** [comment]
same question.

**Comment by chintanckg** [comment]
Same Question. @MonaiThang / @kevinXYX , please share if you have already found somthing

**Comment by MonaiThang** [comment]
I think this project is inactive since the official [libpostal](https://github.com/openvenues/libpostal) is now supports Windows.
I put the related URL here in case someone searches this question and end up stuck at this point.
https://github.com/openvenues/libpostal#installation-windows
